/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-north-1",
    "aws_content_delivery_bucket": "basavresume-20240414111018-hostingbucket-dev",
    "aws_content_delivery_bucket_region": "eu-north-1",
    "aws_content_delivery_url": "https://d259fxu9tdflce.cloudfront.net"
};


export default awsmobile;
