/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-north-1",
    "aws_content_delivery_bucket": "basavresume-20240414111018-hostingbucket-prod",
    "aws_content_delivery_bucket_region": "eu-north-1",
    "aws_content_delivery_url": "https://d1tsmgselt1r8g.cloudfront.net"
};


export default awsmobile;
